name: v1-clean-build
on:
  workflow_dispatch:
   inputs:
      mesa_source:
        description: 'Mesaのソースコードを選択'
        required: true
        default: 'upstream'
        type: choice
        options:
          - upstream
          - ubuntu

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write  # これがリリース作成に必要

jobs:
  command:
    name: Clean build disk images with Mesa for Rockchip
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@main

# 2. ローカルと共通のBASHスクリプトを実行   Mesa deb
      - name: Build all package and disk images
        env: 
           mesa_source: ${{ github.event.inputs.mesa_source }}
        run: |
          mkdir -p build/overlay build/kernel build/images
          cp *.sh build
          cp my-add.txt build/overlay
          cd build
          chmod +x *.sh
          ./main-control.sh $mesa_source
          cd ..
          echo " ------------- overlay -------------------"
          ls build/overlay/
          echo " ------------- kernel --------------------"
          ls build/kernel/
          echo " ------------ images ----------------------"
          ls build/images/

      - name: Get current date
        id: date
        run: echo "now=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Get kernel version
        id: kernel
        run: cat ./build/overlay/kernel_version >> $GITHUB_OUTPUT

      - name: Mesa version
        id: mesa
        run: echo "release_mesa_info=$(cat ./build/overlay/rel.txt)" >> $GITHUB_OUTPUT
        

        # --- リリース直前にこれを追加 ---
      - name: Fix file permissions
        run: sudo chown -R runner:runner ./build/overlay/* ./build/kernel/* ./build/images/*
        # ----------------------------
      
      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          # 実行するたびにユニークなタグ名（例: build-1, build-2...）を付けます
          tag_name: rock-pi-4-${{ github.run_number }}
          name: "Radxa Rock pi 4BDisk Image Build ${{ github.run_number }}"
          body: |
            Radxa Rock pi 4B ディスクイメージ with Mesa for Rockchip
            ビルド日時: ${{ steps.date.outputs.now }}
            ベースカーネル: ${{ steps.kernel.outputs.kernel_version }}
            Mesa バージョン: ${{ steps.mesa.outputs.release_mesa_info }}
          draft: false
          prerelease: false
          # ここに圧縮済みファイルのパスを指定します
          files: |
            ./build/images/Ubuntu-*img.xz 
            ./build/overlay/*.bin
            ./build/kernel/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



